### ISSUE TITLE
Polylang plugin compatibility

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#377]
Hi,

Please refer to this thread.
https://wordpress.org/support/topic/menu-is-shown-in-wrong-language/

I am able to replicate this issue.

I am able to setup other language menu in customizer but after Save and Publish, it immediately reverts back to default language menu.

I believe Hueman theme should at least work with one free multi-language plugin.
Therefore, please look into it when you are able to find time.

Thank you
Denzel

**Comment by Destrega** [comment]
Any news on this?

**Comment by halovic** [comment]
I have the same problem.. It only affects the header and footer menu.

**Comment by FabriceAllard** [comment]
Hello !
I have the same issue since december, and I think since I upgraded to the 3.3.x version of Hueman.
Thanks for working on this...   :-)

**Comment by FabriceAllard** [comment]
For me, the problem is on the 3 menus : Top, Header and Footer.

I think that this page from the Polylang developper already explain how to fix it : 
https://polylang.wordpress.com/2014/04/10/incorrect-usage-of-wp_nav_menu/

**Comment by Destrega** [comment]
@FabriceAllard you are right, i have fixed the problem by doing the following:

in /parts/header-main.php change
wp_nav_menu(
                  array(
                    'theme_location'=>'header',
                    'menu_class'=>'nav container-inner group',
                    'container'=>'',
                    'menu_id' => '',
                    'fallback_cb'=> is_multisite() ? '' : 'hu_page_menu'
                  )
              );
to 
wp_nav_menu(
                  array(
                    'menu_class'=>'nav container-inner group',
                    'container'=>'',
                    'menu_id' => '',
                    'fallback_cb'=> is_multisite() ? '' : 'hu_page_menu'
                  )
              );

in /parts/header-nav-topbar.php change
wp_nav_menu(array('theme_location'=>'topbar','menu_class'=>'nav container-inner group','container'=>'','menu_id' => '','fallback_cb'=> false));
to
wp_nav_menu(array('menu_class'=>'nav container-inner group','container'=>'','menu_id' => '','fallback_cb'=> false));

in footer.php change
wp_nav_menu( array('theme_location'=>'footer','menu_class'=>'nav container group','container'=>'','menu_id'=>'','fallback_cb'=> 'hu_page_menu' ) ); ?>
to
wp_nav_menu( array('menu_class'=>'nav container group','container'=>'','menu_id'=>'','fallback_cb'=> 'hu_page_menu' ) ); ?>

**Comment by FabriceAllard** [comment]
Thanks a lot !!
You mean... it should be fixed in a new release coming soon ?

**Comment by FabriceAllard** [comment]
New information : I've juste downloaded the 3.3.4 of Hueman, the problem is still here but I notice that when I deactivate the Hueman Addons (2.0.7), then everything is OK !!
My Polylang is also updated to v2.1.1.
Then the problem seems to be in the Hueman Addons, not Hueman

**Comment by Nikeo** [comment]
@eri-trabiccolo does it sound familiar ? Isn't this something we already fixed in Customizr ?
Let me know when you'll get the chance

**Comment by FabriceAllard** [comment]
@Nikeo I've just given another chance to Customizr by re-installing it, and indeed there is no problem with Polylang. The problem is only in Hueman / Hueman Addons.

**Comment by AlexBrtn** [comment]
@Nikeo To begin with - thanks for the template.
The problem is still actual. https://antidk.org.ua/en/ (menu the menu is not English). Please fix.
Hueman v3.3.6
Polylang v2.1.1

**Comment by daviddwd8** [comment]
@Nikeo
I confirm that the bug still exist.
@Destrega 
Your solution doesn't work for me. In fact, with your fix menus are the same for all port (head, main, footer).

Thank you

**Comment by fwolfst** [comment]
I can confirm this issue. The theme is implemented as requested by the polylang docs afaics. Also, disabling the hueman-addons plugins resolved it for me in some quick tests.

**Comment by libengine** [comment]
I checked this issue with new, almost empty WP-installation.
WP 4.7.3, Polylang 2.1.2, Hueman Addons 2.0.9, Hueman 3.3.7
Disabling Hueman Addons 'solves' the problem.

**Comment by fwolfst** [comment]
@Nikeo As far as i can see the milestone (3.3.8) was missed, right?
Still not working with addons .10, but for everybody who does not need advanced per-site menu customizr-customization and is not afraid of tiny code changes, I put an outline of how to workaround this issue in: https://github.com/presscustomizr/hueman-addons/issues/34 .

**Comment by Birnou** [comment]
@Nikeo , please,do you have any news concerning the uise of Polylang with Hueman?
I've posted a thread on the forum
https://wordpress.org/support/topic/using-polylang-with-hueman-cant-change-top-and-main-menu/#post-9471143
thanks for your attention... have a nice day... birnou

**Comment by denzelchia** [comment]
Hi @Nikeo 

A Hueman Pro theme user reporting the same issue on helpscout.
https://secure.helpscout.net/conversation/444607348/33026/?folderId=607546#thread-1205533236

Thank you

**Comment by denzelchia** [comment]
Hi @Nikeo 

Another Hueman Pro Theme user reporting the same issue on helpscout.
https://secure.helpscout.net/conversation/449553533/33362/?folderId=607546#thread-1217936142

Thank you

**Comment by ghost** [comment]
related to https://github.com/presscustomizr/hueman-addons/issues/34

**Comment by ghost** [comment]
fixed in https://github.com/presscustomizr/hueman-addons/commit/3728cfe4a56e194f856ae67cf174073f94792123
